import Head from "next/head";
import Image from "next/image";
import StartPage from "../src/components/startpage/StartPage";
import styles from "../styles/Home.module.css";
import { useContext, useEffect } from "react";

import { MyContext } from "../src/contexts/MyContext";
import { useAuth0 } from "@auth0/auth0-react";
import LoginText from "../src/components/common/LoginText";
import StartPage2 from "../src/components/startpage/StartPage2";

const Home = () => {
  const { setUserID } = useContext(MyContext);
  const { user, isAuthenticated } = useAuth0();
  useEffect(() => {
    setUserID(user);
  });
  return (
    <>
      {/* <div className={styles.container}> */}
      <Head>
        <title>Verktøyregister</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StartPage />

      {/* {user && user.sub === process.env.USER_SUB && <LoginText />} */}
      {/* </div> */}
    </>
  );
};

export default Home;
